(package "applescript-mode"
         "0.1"
         "major mode for editing AppleScript source")

(website-url "https://github.com/emacsorphanage/applescript-mode")
(keywords "languages" "tools")

(package-file "applescript-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
